// VerifyScreen.tsx: checks the real seal on a SealedReport via POST /creva-score/verify
// (gateway/src/index.ts:75-82). Reached either with a report just generated by QueryScreen, or
// with none at all (e.g. the "Crédito" tab's shortcut) — in the second case there is nothing to
// verify and the screen says so instead of showing an invented report. The verify route is
// x402-gated the same way /creva-score/report is, and this app has no wallet signer yet (see
// docs/plan.md), so a real check here will legitimately come back "payment required" until one
// exists.
import * as Haptics from "expo-haptics";
import { useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { Card, Section } from "../query/components/VisualPrimitives";
import { VerifyReportCard } from "./components/VerifyReportCard";
import { SealedReport, VerifyResult, verifySealedReport } from "./sealClient";
import { BackButton } from "../shared/BackButton";

type Phase = "loading" | "payment_required" | "verified" | "error" | "empty";

export function VerifyScreen({ sealedReport, onBack }: { sealedReport: SealedReport | null; onBack?: () => void }) {
  const [phase, setPhase] = useState<Phase>(sealedReport ? "loading" : "empty");
  const [result, setResult] = useState<VerifyResult | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  useEffect(() => {
    if (!sealedReport) {
      setPhase("empty");
      return;
    }

    let cancelled = false;
    setPhase("loading");

    verifySealedReport(sealedReport)
      .then((res) => {
        if (cancelled) return;
        setResult(res);
        if (res.status === 402) {
          setPhase("payment_required");
          return;
        }
        setPhase("verified");
        if (res.verification.content === "intact" && res.verification.signature === "valid") {
          Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
        } else {
          Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
        }
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setErrorMessage(err instanceof Error ? err.message : "No se pudo verificar el sello.");
        setPhase("error");
      });

    return () => {
      cancelled = true;
    };
  }, [sealedReport]);

  if (phase === "loading") {
    return (
      <SafeAreaView className="flex-1 items-center justify-center bg-bg" edges={["top", "bottom"]}>
        <ActivityIndicator testID="verify-loading" />
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView className="flex-1 bg-bg" edges={["top", "bottom"]}>
      <ScrollView className="flex-1" contentContainerClassName="px-6 pb-10 pt-6" testID="verify-screen">
        {onBack ? <BackButton onPress={onBack} /> : null}
        <View className="mb-8">
          <Text className="text-xs font-bold uppercase text-text/60">Verificación pública</Text>
          <Text className="mt-2 text-3xl font-bold text-text">Comprobar un reporte</Text>
          <Text className="mt-2 text-base leading-6 text-text/70">
            Un veredicto de contenido, un veredicto de firma y los límites de lo que el sello puede acreditar.
          </Text>
        </View>

        {phase === "empty" && (
          <Section title="Nada que comprobar todavía">
            <Card testID="verify-empty">
              <Text className="text-sm leading-5 text-text/70">
                Genera un reporte sellado desde la consulta pagada para poder verificarlo aquí.
              </Text>
            </Card>
          </Section>
        )}

        {phase === "error" && (
          <Section title="No se pudo verificar">
            <Card testID="verify-error">
              <Text className="text-sm leading-5 text-crimson">{errorMessage ?? "Ocurrió un error inesperado."}</Text>
            </Card>
          </Section>
        )}

        {phase === "payment_required" && result?.status === 402 && (
          <Section title="Pago requerido" lead="Verificar el sello también pasa por el reto x402 del gateway.">
            <Card testID="verify-payment-required">
              <View className="rounded-xl bg-warning/10 p-3">
                <Text className="font-bold text-warning-text">402 Pago requerido</Text>
                <Text className="mt-1 text-sm leading-5 text-warning-text">
                  {result.accepts[0]?.maxAmountRequired} {result.accepts[0]?.asset} en {result.accepts[0]?.network}
                </Text>
              </View>
              <Text className="mt-3 text-sm leading-5 text-text/70">
                No hay una billetera Hedera conectada para liquidar este pago todavía.
              </Text>
            </Card>
          </Section>
        )}

        {phase === "verified" && result?.status === 200 && sealedReport && (
          <VerifyReportCard verification={result.verification} sealed={sealedReport} />
        )}
      </ScrollView>
    </SafeAreaView>
  );
}
